### ISSUE TITLE
能不能获取弹幕是否 disposed 呢？

### ISSUE THREAD

**Issue by Seifon** [danielwii/flutter_barrage#4]
```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: A BarrageWallController was used after being disposed.
Once you have called dispose() on a BarrageWallController, it can no longer be used.
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:105:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:111:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:200:12)
#3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:270:5)
#4      BarrageWallController.tryFire (package:flutter_barrage/flutter_barrage.dart:319:9)
#5      BarrageWallController.send (package:flutter_barrage/flutter_barrage.dart:330:5)
```

**Comment by danielwii** [comment]
目前 controller 是在完成后自己 dispose 的。
我想应该可以增加一个标记位，如果是外部传入的 controller 由用户自己 dispose。

**Comment by Seifon** [comment]
是的，这个应该让我们自己手动调用disport比较好。如果有个标记位也是挺好的

**Comment by danielwii** [comment]
0.3.0 已经 release 了，可以升级试试。
