### ISSUE TITLE
java.lang.Throwable _BarrageState#5ed2c(tickers: tracking 1 ticker) was disposed with an active Ticker. 

### ISSUE THREAD

**Issue by Seifon** [danielwii/flutter_barrage#8]
```
java.lang.Throwable
_BarrageState#5ed2c(tickers: tracking 1 ticker) was disposed with an active Ticker. _BarrageState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. All Tickers must be disposed before calling super.dispose(). Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak. The offending ticker was: _WidgetTicker(created by _BarrageState#5ed2c(tickers: tracking 0 tickers)) The stack trace when the _WidgetTicker was actually created was: #0 new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:64:40) #1 new Ticker (package:flutter/src/scheduler/ticker.dart:66:6) #2 new _WidgetTicker (package:flutter/src/widgets/ticker_provider.dart:225:80) #3 __BarrageState&State&TickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:161:34) #4 new AnimationController [Message over limit siz...too long be cutted!
```

错误日志：

```

1 Dart.0 __BarrageState&State&TickerProviderStateMixin.dispose.<anonymous closure>(package:flutter/src/widgets/ticker_provider.dart:178)
--
2 Dart.1 __BarrageState&State&TickerProviderStateMixin.dispose(package:flutter/src/widgets/ticker_provider.dart:191)
3 Dart.2 _BarrageState.dispose(package:flutter_barrage/flutter_barrage.dart:310)
4 Dart.3 StatefulElement.unmount(package:flutter/src/widgets/framework.dart:3916)
5 Dart.4 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1697)
6 Dart.5 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
7 Dart.6 ComponentElement.visitChildren(package:flutter/src/widgets/framework.dart:3770)
8 Dart.7 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
9 Dart.8 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
10 Dart.9 ComponentElement.visitChildren(package:flutter/src/widgets/framework.dart:3770)
11 Dart.10 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
12 Dart.11 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
13 Dart.12 MultiChildRenderObjectElement.visitChildren(package:flutter/src/widgets/framework.dart:4965)
14 Dart.13 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
15 Dart.14 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
16 Dart.15 ComponentElement.visitChildren(package:flutter/src/widgets/framework.dart:3770)
17 Dart.16 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
18 Dart.17 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
19 Dart.18 ComponentElement.visitChildren(package:flutter/src/widgets/framework.dart:3770)
20 Dart.19 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
21 Dart.20 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
22 Dart.21 SingleChildRenderObjectElement.visitChildren(package:flutter/src/widgets/framework.dart:4864)
23 Dart.22 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
24 Dart.23 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
25 Dart.24 SingleChildRenderObjectElement.visitChildren(package:flutter/src/widgets/framework.dart:4864)
26 Dart.25 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
27 Dart.26 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
28 Dart.27 ComponentElement.visitChildren(package:flutter/src/widgets/framework.dart:3770)
29 Dart.28 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
30 Dart.29 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
31 Dart.30 ComponentElement.visitChildren(package:flutter/src/widgets/framework.dart:3770)
32 Dart.31 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
33 Dart.32 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
34 Dart.33 ComponentElement.visitChildren(package:flutter/src/widgets/framework.dart:3770)
35 Dart.34 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
36 Dart.35 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
37 Dart.36 MultiChildRenderObjectElement.visitChildren(package:flutter/src/widgets/framework.dart:4965)
38 Dart.37 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
39 Dart.38 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
40 Dart.39 ComponentElement.visitChildren(package:flutter/src/widgets/framework.dart:3770)
41 Dart.40 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
42 Dart.41 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
43 Dart.42 ComponentElement.visitChildren(package:flutter/src/widgets/framework.dart:3770)
44 Dart.43 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
45 Dart.44 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
46 Dart.45 SingleChildRenderObjectElement.visitChildren(package:flutter/src/widgets/framework.dart:4864)
47 Dart.46 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
48 Dart.47 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
49 Dart.48 ComponentElement.visitChildren(package:flutter/src/widgets/framework.dart:3770)
50 Dart.49 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
51 Dart.50 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
52 Dart.51 SingleChildRenderObjectElement.visitChildren(package:flutter/src/widgets/framework.dart:4864)
53 Dart.52 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
54 Dart.53 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
55 Dart.54 ComponentElement.visitChildren(package:flutter/src/widgets/framework.dart:3770)
56 Dart.55 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
57 Dart.56 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
58 Dart.57 ComponentElement.visitChildren(package:flutter/src/widgets/framework.dart:3770)
59 Dart.58 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
60 Dart.59 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
61 Dart.60 ComponentElement.visitChildren(package:flutter/src/widgets/framework.dart:3770)
62 Dart.61 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
63 Dart.62 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
64 Dart.63 ComponentElement.visitChildren(package:flutter/src/widgets/framework.dart:3770)
65 Dart.64 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
66 Dart.65 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
67 Dart.66 ComponentElement.visitChildren(package:flutter/src/widgets/framework.dart:3770)
68 Dart.67 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
69 Dart.68 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
70 Dart.69 MultiChildRenderObjectElement.visitChildren(package:flutter/src/widgets/framework.dart:4965)
71 Dart.70 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
72 Dart.71 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
73 Dart.72 ComponentElement.visitChildren(package:flutter/src/widgets/framework.dart:3770)
74 Dart.73 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
75 Dart.74 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
76 Dart.75 ComponentElement.visitChildren(package:flutter/src/widgets/framework.dart:3770)
77 Dart.76 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
78 Dart.77 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
79 Dart.78 ComponentElement.visitChildren(package:flutter/src/widgets/framework.dart:3770)
80 Dart.79 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
81 Dart.80 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
82 Dart.81 SingleChildRenderObjectElement.visitChildren(package:flutter/src/widgets/framework.dart:4864)
83 Dart.82 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
84 Dart.83 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
85 Dart.84 ComponentElement.visitChildren(package:flutter/src/widgets/framework.dart:3770)
86 Dart.85 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
87 Dart.86 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
88 Dart.87 SingleChildRenderObjectElement.visitChildren(package:flutter/src/widgets/framework.dart:4864)
89 Dart.88 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
90 Dart.89 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
91 Dart.90 ComponentElement.visitChildren(package:flutter/src/widgets/framework.dart:3770)
92 Dart.91 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
93 Dart.92 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
94 Dart.93 ComponentElement.visitChildren(package:flutter/src/widgets/framework.dart:3770)
95 Dart.94 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
96 Dart.95 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
97 Dart.96 ComponentElement.visitChildren(package:flutter/src/widgets/framework.dart:3770)
98 Dart.97 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
99 Dart.98 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
100 Dart.99 ComponentElement.visitChildren(package:flutter/src/widgets/framework.dart:3770)
101 Dart.100 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
102 Dart.101 _InactiveElements._unmount.<anonymous closure>(package:flutter/src/widgets/framework.dart:1695)
103 Dart.102 ComponentElement.visitChildren(package:flutter/src/widgets/framework.dart:3770)
104 Dart.103 _InactiveElements._unmount(package:flutter/src/widgets/framework.dart:1693)
105 Dart.104 ListIterable.forEach(dart:_internal/iterable.dart:39)
106 Dart.105 _InactiveElements._unmountAll(package:flutter/src/widgets/framework.dart:1706)
107 Dart.106 BuildOwner.finalizeTree.<anonymous closure>(package:flutter/src/widgets/framework.dart:2364)
108 Dart.107 BuildOwner.lockState(package:flutter/src/widgets/framework.dart:2196)
109 Dart.108 BuildOwner.finalizeTree(package:flutter/src/widgets/framework.dart:2363)
110 Dart.109 _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame(package:flutter/src/widgets/binding.dart:702)
111 Dart.110 _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback(package:flutter/src/rendering/binding.dart:286)
112 Dart.111 _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback(package:flutter/src/scheduler/binding.dart:1012)
113 Dart.112 _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame(package:flutter/src/scheduler/binding.dart:952)
114 Dart.113 _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame(package:flutter/src/scheduler/binding.dart:864)
115 Dart.114 _rootRun(dart:async/zone.dart:1124)
116 Dart.115 _CustomZone.run(dart:async/zone.dart:1021)
117 Dart.116 _CustomZone.runGuarded(dart:async/zone.dart:923)
118 Dart.117 _invoke(dart:ui/hooks.dart:219)
119 Dart.118 _drawFrame(dart:ui/hooks.dart:178)


```

**Comment by Seifon** [comment]
```
使用时长

17 分 10 秒
前后台状态

后台
设备机型

波导 M10
系统版本

Android 7.0,level 19
ROM

alps/bestone82_wet_kk
CPU架构

armeabi-v7a
```

**Comment by danielwii** [comment]
controller 是在哪里 dispose 的？能贴一下那里的代码吗？

**Comment by Seifon** [comment]
代码里没有调过这个方法，应该是插件销毁时，系统调了

**Comment by danielwii** [comment]
看报错应该是 _BarrageState 销毁的时候 controller 并没有调用 dispose。
